language: python

python:
  - 3.4
  - 3.5

env:
  - NUMPY_VERSION=1.9
  - NUMPY_VERSION=1.11.0

# Tools to install:
addons:
  apt:
    packages:
    - bc

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pylint numpy=$NUMPY_VERSION pandas

# Command to run tests:
script:
  - cd python
  - pip install -e .
  - py.test
  - py.test cheeseshop --doctest-modules
  - bash run_pylint.sh cheeseshop 8.0
