language: python

python:
  - 3.4
  - 3.5

env:
  - NUMPY_VERSION=1.9
  - NUMPY_VERSION=1.11.0

# Tools to install:
addons:
  apt:
    packages:
    - bc

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - CONDADIR=$HOME/miniconda2
  - ./miniconda.sh -b -p $CONDADIR
  - export PATH=$CONDADIR/bin:$PATH
  # Update conda itself
  - conda update --yes conda

# Install packages
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy=$NUMPY_VERSION pandas pylint
  - source activate env_name
  - pip install pytest  pytest-cov codecov

# Command to run tests:
script:
  - cd python
  - pip install -e .
  - py.test
  - py.test cheeseshop --doctest-modules
  - codecov
  - bash run_pylint.sh cheeseshop 8.0

after_success:
  - codecov