language: python
python: "3.5"
# Tools to install:
addons:
  apt:
    packages:
    - bc
# Command to run tests:
script:
  - cd python
  - pip install -e .
  - py.test
  - py.test cheeseshop --doctest-modules
  - bash run_pylint.sh cheeseshop 8.0
